export const tokens = {
  ASSIGN: /(:=)/,
  COMMENT_LINE: /([/]{2}[^\n]*\n)/,
  DOT: /(\.)/,
  NUM: /[0-9]{1,8}/,
  FLOAT: /[0-9]{1,8}\.[0-9]{1,5}/,
  SUM: /[+]/,
  MINUS: /[-]/,
  MULTIPLY: /[*]/,
  DIVIDE: /[/]/,
  IDENTIFIER: /([_]*[a-zA-Z0-9_]{1,15})/,
  COMMENT_BLOCK:/({[^]*})/,
  OPEN_PARENTHESIS: /[(]/,
  CLOSE_PARENTHESIS: /[)]/,
  // PARENTHESIS_BLOCK:/(\([^\)\(]*\))/,
  COLON: /(:)/,
  COMMA: /(,)/,
  SEMICOLON: /(;)/,
  EQUAL: /(=)/,
  SMALLER: /(<)/,
  BIGGER: /(>)/,
  DIFFERENT: /(<>)/,
  SMALLER_OR_EQUAL: /(<=)/,
  BIGGER_OR_EQUAL: /(>=)/,
  WHITESPACE: /\s/
}